"""Add visibility_policy_id to Group

Revision ID: 7dd674dfd5af
Revises: 003
Create Date: 2026-05-31 01:39:03.771220
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dd674dfd5af'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_nodes', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='node_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'TODO'::node_status_enum"))
    op.alter_column('activity_nodes', 'progress',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('activity_nodes', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('activity_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_activity_nodes_parent', table_name='activity_nodes')
    op.drop_index('ix_activity_nodes_project', table_name='activity_nodes')
    op.alter_column('challenges', 'status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'FAILED', 'EXPIRED', name='challenge_status_enum'),
               nullable=False)
    op.alter_column('challenges', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('challenges', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('competitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'REGISTRATION_OPEN', 'IN_PROGRESS', 'JUDGING', 'COMPLETED', 'CANCELLED', name='event_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'PLANNED'::event_status_enum"))
    op.alter_column('events', 'result_sync_state',
               existing_type=postgresql.ENUM('NOT_SYNCED', 'SYNCING', 'SYNCED', 'ERROR', name='sync_state_enum'),
               nullable=False,
               existing_server_default=sa.text("'NOT_SYNCED'::sync_state_enum"))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_memberships', 'membership_role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='membership_role_enum'),
               nullable=False,
               existing_server_default=sa.text("'MEMBER'::membership_role_enum"))
    op.alter_column('group_memberships', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_group_memberships_group', table_name='group_memberships')
    op.drop_index('ix_group_memberships_user', table_name='group_memberships')
    op.add_column('groups', sa.Column('visibility_policy_id', sa.Uuid(), nullable=True))
    op.alter_column('groups', 'is_temporary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'groups', 'visibility_policies', ['visibility_policy_id'], ['id'])
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_unread', table_name='notifications')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.alter_column('participants', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('participants', 'status',
               existing_type=postgresql.ENUM('REGISTERED', 'CONFIRMED', 'WITHDRAWN', name='participant_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'REGISTERED'::participant_status_enum"))
    op.drop_index('ix_participants_competition', table_name='participants')
    op.alter_column('projects', 'progress_percent',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='project_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::project_status_enum"))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_ratings_schedule_id', table_name='ratings')
    op.alter_column('schedules', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('schedules', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Asia/Seoul'::character varying"))
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='schedule_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'SCHEDULED'::schedule_status_enum"))
    op.alter_column('schedules', 'importance_score',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'50'::smallint"))
    op.alter_column('schedules', 'base_importance',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'50'::smallint"))
    op.alter_column('schedules', 'authority_weight',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'urgency_weight',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'feedback_weight',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'dependency_weight',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_schedules_creator_id', table_name='schedules')
    op.drop_index('ix_schedules_importance', table_name='schedules')
    op.drop_index('ix_schedules_project_id', table_name='schedules')
    op.drop_index('ix_schedules_start_at', table_name='schedules')
    op.drop_index('ix_schedules_subtype', table_name='schedules')
    op.drop_index('ix_schedules_type', table_name='schedules')
    op.alter_column('scoreboards', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('scoreboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_jobs', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='sync_job_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::sync_job_status_enum"))
    op.alter_column('sync_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('visibility_policies', 'allow_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('visibility_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visibility_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('visibility_policies', 'allow_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('sync_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_jobs', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='sync_job_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::sync_job_status_enum"))
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scoreboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scoreboards', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_schedules_type', 'schedules', ['type'], unique=False)
    op.create_index('ix_schedules_subtype', 'schedules', ['subtype'], unique=False)
    op.create_index('ix_schedules_start_at', 'schedules', ['start_at'], unique=False)
    op.create_index('ix_schedules_project_id', 'schedules', ['project_id'], unique=False)
    op.create_index('ix_schedules_importance', 'schedules', ['importance_score'], unique=False)
    op.create_index('ix_schedules_creator_id', 'schedules', ['creator_id'], unique=False)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'dependency_weight',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'feedback_weight',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'urgency_weight',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'authority_weight',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'base_importance',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'50'::smallint"))
    op.alter_column('schedules', 'importance_score',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'50'::smallint"))
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='schedule_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'SCHEDULED'::schedule_status_enum"))
    op.alter_column('schedules', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Asia/Seoul'::character varying"))
    op.alter_column('schedules', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_ratings_schedule_id', 'ratings', ['schedule_id'], unique=False)
    op.alter_column('ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='project_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::project_status_enum"))
    op.alter_column('projects', 'progress_percent',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.create_index('ix_participants_competition', 'participants', ['competition_id'], unique=False)
    op.alter_column('participants', 'status',
               existing_type=postgresql.ENUM('REGISTERED', 'CONFIRMED', 'WITHDRAWN', name='participant_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'REGISTERED'::participant_status_enum"))
    op.alter_column('participants', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('groups', 'is_temporary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('groups', 'visibility_policy_id')
    op.create_index('ix_group_memberships_user', 'group_memberships', ['user_id'], unique=False)
    op.create_index('ix_group_memberships_group', 'group_memberships', ['group_id'], unique=False)
    op.alter_column('group_memberships', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_memberships', 'membership_role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='membership_role_enum'),
               nullable=True,
               existing_server_default=sa.text("'MEMBER'::membership_role_enum"))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'result_sync_state',
               existing_type=postgresql.ENUM('NOT_SYNCED', 'SYNCING', 'SYNCED', 'ERROR', name='sync_state_enum'),
               nullable=True,
               existing_server_default=sa.text("'NOT_SYNCED'::sync_state_enum"))
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'REGISTRATION_OPEN', 'IN_PROGRESS', 'JUDGING', 'COMPLETED', 'CANCELLED', name='event_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'PLANNED'::event_status_enum"))
    op.alter_column('competitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('challenges', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('challenges', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('challenges', 'status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'FAILED', 'EXPIRED', name='challenge_status_enum'),
               nullable=True)
    op.create_index('ix_activity_nodes_project', 'activity_nodes', ['project_id'], unique=False)
    op.create_index('ix_activity_nodes_parent', 'activity_nodes', ['parent_id'], unique=False)
    op.alter_column('activity_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activity_nodes', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('activity_nodes', 'progress',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('activity_nodes', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='node_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'TODO'::node_status_enum"))
    # ### end Alembic commands ###
