"""Add EV simulator fields to ActivityNode

Revision ID: 94e402c43bfa
Revises: 7dd674dfd5af
Create Date: 2026-05-30 17:23:04.031768
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e402c43bfa'
down_revision: Union[str, None] = '7dd674dfd5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_nodes', sa.Column('cost_hours', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('activity_nodes', sa.Column('success_probability', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('activity_nodes', sa.Column('reward_points', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_nodes', 'reward_points')
    op.drop_column('activity_nodes', 'success_probability')
    op.drop_column('activity_nodes', 'cost_hours')
    # ### end Alembic commands ###
